#!/bin/bash
#
# Deterministic generator for the test-debt-100-failures fixture.
# Produces pytest.ini and test_synthetic.py with 100 failing tests across 5 categories.
#
# Run from the fixture directory:
#   cd tests/fixtures/test-debt-100-failures
#   bash generate.sh
#
# Idempotent — running it again overwrites with byte-identical output.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ─── pytest.ini ───────────────────────────────────────────────────────────────

cat > pytest.ini <<'EOF'
[pytest]
# Minimal config — exists primarily so /prism's runner-detection picks pytest
# for this fixture directory. No collection paths configured; pytest defaults
# (test_*.py / *_test.py) handle test_synthetic.py.
addopts = --tb=line --no-header
EOF

# ─── test_synthetic.py ────────────────────────────────────────────────────────

{
    cat <<'HEADER'
"""
Synthetic pytest fixture for AC11 (subagent return-message ≤ 2K tokens).

100 failing tests distributed across 5 plausible categories (20 each):

  1. real-issue              — assertions that catch a real (synthetic) bug
  2. test-infrastructure-broken — collection / import / setup errors
  3. drift                   — references to renamed / moved / removed symbols
  4. abandoned               — tests for features that don't exist
  5. quarantine-candidate    — timing-dependent / non-deterministic

These tests are NOT meant to be reasonable specifications of any real system.
They exist solely to give the test-debt-classifier 100 distinct failures to
classify and to stress the 2K-token output bound.

Generated by tests/fixtures/test-debt-100-failures/generate.sh — do not hand-edit.
"""

import time

HEADER

    # ─── Category 1: real-issue (20 tests) ─────────────────────────────────────
    echo ""
    echo "# ─── Category 1: real-issue (assertion failures, sound logic) ─────────────"
    echo ""
    for i in $(seq 1 20); do
        cat <<EOF
def test_real_issue_${i}():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = ${i} * 2
    actual = ${i} + ${i} - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

EOF
    done

    # ─── Category 2: test-infrastructure-broken (20 tests) ─────────────────────
    echo "# ─── Category 2: test-infrastructure-broken (import/fixture errors) ──────"
    echo ""
    # Use a single import that will fail at collection time
    echo "try:"
    echo "    from nonexistent_package_for_classifier_fixture import frobnicate"
    echo "except ImportError:"
    echo "    frobnicate = None  # Tests below will fail on AttributeError-style usage"
    echo ""
    for i in $(seq 1 20); do
        cat <<EOF
def test_infra_broken_${i}():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(${i})

EOF
    done

    # ─── Category 3: drift (20 tests) ──────────────────────────────────────────
    echo "# ─── Category 3: drift (references to renamed/moved symbols) ─────────────"
    echo ""
    for i in $(seq 1 20); do
        cat <<EOF
def test_drift_${i}():
    """drift: test references symbol 'old_compute_v${i}' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v${i}
    except ImportError:
        raise AssertionError(f"symbol old_compute_v${i} no longer exists in synthetic_module — likely renamed in commit history")

EOF
    done

    # ─── Category 4: abandoned (20 tests) ──────────────────────────────────────
    echo "# ─── Category 4: abandoned (testing features that never shipped) ─────────"
    echo ""
    for i in $(seq 1 20); do
        cat <<EOF
def test_abandoned_${i}():
    """abandoned: tests a feature 'experimental_widget_${i}' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget${i}
    except ImportError:
        raise AssertionError(f"ExperimentalWidget${i} was reverted in synthetic_module — feature abandoned")

EOF
    done

    # ─── Category 5: quarantine-candidate (20 tests) ───────────────────────────
    echo "# ─── Category 5: quarantine-candidate (timing-dependent flakes) ──────────"
    echo ""
    for i in $(seq 1 20); do
        # Use a deterministic-but-flake-shaped condition
        cat <<EOF
def test_quarantine_candidate_${i}():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

EOF
    done

} > test_synthetic.py

echo "Generated:"
echo "  pytest.ini       ($(wc -l < pytest.ini) lines)"
echo "  test_synthetic.py ($(wc -l < test_synthetic.py) lines, $(grep -c '^def test_' test_synthetic.py) test functions)"
