"""
Synthetic pytest fixture for AC11 (subagent return-message ≤ 2K tokens).

100 failing tests distributed across 5 plausible categories (20 each):

  1. real-issue              — assertions that catch a real (synthetic) bug
  2. test-infrastructure-broken — collection / import / setup errors
  3. drift                   — references to renamed / moved / removed symbols
  4. abandoned               — tests for features that don't exist
  5. quarantine-candidate    — timing-dependent / non-deterministic

These tests are NOT meant to be reasonable specifications of any real system.
They exist solely to give the test-debt-classifier 100 distinct failures to
classify and to stress the 2K-token output bound.

Generated by tests/fixtures/test-debt-100-failures/generate.sh — do not hand-edit.
"""

import time


# ─── Category 1: real-issue (assertion failures, sound logic) ─────────────

def test_real_issue_1():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 1 * 2
    actual = 1 + 1 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_2():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 2 * 2
    actual = 2 + 2 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_3():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 3 * 2
    actual = 3 + 3 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_4():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 4 * 2
    actual = 4 + 4 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_5():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 5 * 2
    actual = 5 + 5 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_6():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 6 * 2
    actual = 6 + 6 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_7():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 7 * 2
    actual = 7 + 7 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_8():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 8 * 2
    actual = 8 + 8 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_9():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 9 * 2
    actual = 9 + 9 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_10():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 10 * 2
    actual = 10 + 10 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_11():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 11 * 2
    actual = 11 + 11 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_12():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 12 * 2
    actual = 12 + 12 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_13():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 13 * 2
    actual = 13 + 13 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_14():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 14 * 2
    actual = 14 + 14 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_15():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 15 * 2
    actual = 15 + 15 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_16():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 16 * 2
    actual = 16 + 16 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_17():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 17 * 2
    actual = 17 + 17 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_18():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 18 * 2
    actual = 18 + 18 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_19():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 19 * 2
    actual = 19 + 19 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

def test_real_issue_20():
    """Real-issue: arithmetic invariant violated by intentional bug."""
    expected = 20 * 2
    actual = 20 + 20 - 1   # Off-by-one bug under test
    assert actual == expected, f"expected {expected}, got {actual}"

# ─── Category 2: test-infrastructure-broken (import/fixture errors) ──────

try:
    from nonexistent_package_for_classifier_fixture import frobnicate
except ImportError:
    frobnicate = None  # Tests below will fail on AttributeError-style usage

def test_infra_broken_1():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(1)

def test_infra_broken_2():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(2)

def test_infra_broken_3():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(3)

def test_infra_broken_4():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(4)

def test_infra_broken_5():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(5)

def test_infra_broken_6():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(6)

def test_infra_broken_7():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(7)

def test_infra_broken_8():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(8)

def test_infra_broken_9():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(9)

def test_infra_broken_10():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(10)

def test_infra_broken_11():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(11)

def test_infra_broken_12():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(12)

def test_infra_broken_13():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(13)

def test_infra_broken_14():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(14)

def test_infra_broken_15():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(15)

def test_infra_broken_16():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(16)

def test_infra_broken_17():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(17)

def test_infra_broken_18():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(18)

def test_infra_broken_19():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(19)

def test_infra_broken_20():
    """test-infrastructure-broken: depends on missing import (collection-adjacent)."""
    assert frobnicate is not None, "missing dependency: nonexistent_package_for_classifier_fixture"
    frobnicate(20)

# ─── Category 3: drift (references to renamed/moved symbols) ─────────────

def test_drift_1():
    """drift: test references symbol 'old_compute_v1' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v1
    except ImportError:
        raise AssertionError(f"symbol old_compute_v1 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_2():
    """drift: test references symbol 'old_compute_v2' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v2
    except ImportError:
        raise AssertionError(f"symbol old_compute_v2 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_3():
    """drift: test references symbol 'old_compute_v3' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v3
    except ImportError:
        raise AssertionError(f"symbol old_compute_v3 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_4():
    """drift: test references symbol 'old_compute_v4' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v4
    except ImportError:
        raise AssertionError(f"symbol old_compute_v4 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_5():
    """drift: test references symbol 'old_compute_v5' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v5
    except ImportError:
        raise AssertionError(f"symbol old_compute_v5 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_6():
    """drift: test references symbol 'old_compute_v6' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v6
    except ImportError:
        raise AssertionError(f"symbol old_compute_v6 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_7():
    """drift: test references symbol 'old_compute_v7' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v7
    except ImportError:
        raise AssertionError(f"symbol old_compute_v7 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_8():
    """drift: test references symbol 'old_compute_v8' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v8
    except ImportError:
        raise AssertionError(f"symbol old_compute_v8 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_9():
    """drift: test references symbol 'old_compute_v9' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v9
    except ImportError:
        raise AssertionError(f"symbol old_compute_v9 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_10():
    """drift: test references symbol 'old_compute_v10' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v10
    except ImportError:
        raise AssertionError(f"symbol old_compute_v10 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_11():
    """drift: test references symbol 'old_compute_v11' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v11
    except ImportError:
        raise AssertionError(f"symbol old_compute_v11 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_12():
    """drift: test references symbol 'old_compute_v12' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v12
    except ImportError:
        raise AssertionError(f"symbol old_compute_v12 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_13():
    """drift: test references symbol 'old_compute_v13' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v13
    except ImportError:
        raise AssertionError(f"symbol old_compute_v13 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_14():
    """drift: test references symbol 'old_compute_v14' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v14
    except ImportError:
        raise AssertionError(f"symbol old_compute_v14 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_15():
    """drift: test references symbol 'old_compute_v15' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v15
    except ImportError:
        raise AssertionError(f"symbol old_compute_v15 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_16():
    """drift: test references symbol 'old_compute_v16' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v16
    except ImportError:
        raise AssertionError(f"symbol old_compute_v16 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_17():
    """drift: test references symbol 'old_compute_v17' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v17
    except ImportError:
        raise AssertionError(f"symbol old_compute_v17 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_18():
    """drift: test references symbol 'old_compute_v18' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v18
    except ImportError:
        raise AssertionError(f"symbol old_compute_v18 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_19():
    """drift: test references symbol 'old_compute_v19' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v19
    except ImportError:
        raise AssertionError(f"symbol old_compute_v19 no longer exists in synthetic_module — likely renamed in commit history")

def test_drift_20():
    """drift: test references symbol 'old_compute_v20' that has been renamed/removed."""
    # Simulated: what was once an importable function is now gone
    try:
        from synthetic_module import old_compute_v20
    except ImportError:
        raise AssertionError(f"symbol old_compute_v20 no longer exists in synthetic_module — likely renamed in commit history")

# ─── Category 4: abandoned (testing features that never shipped) ─────────

def test_abandoned_1():
    """abandoned: tests a feature 'experimental_widget_1' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget1
    except ImportError:
        raise AssertionError(f"ExperimentalWidget1 was reverted in synthetic_module — feature abandoned")

def test_abandoned_2():
    """abandoned: tests a feature 'experimental_widget_2' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget2
    except ImportError:
        raise AssertionError(f"ExperimentalWidget2 was reverted in synthetic_module — feature abandoned")

def test_abandoned_3():
    """abandoned: tests a feature 'experimental_widget_3' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget3
    except ImportError:
        raise AssertionError(f"ExperimentalWidget3 was reverted in synthetic_module — feature abandoned")

def test_abandoned_4():
    """abandoned: tests a feature 'experimental_widget_4' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget4
    except ImportError:
        raise AssertionError(f"ExperimentalWidget4 was reverted in synthetic_module — feature abandoned")

def test_abandoned_5():
    """abandoned: tests a feature 'experimental_widget_5' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget5
    except ImportError:
        raise AssertionError(f"ExperimentalWidget5 was reverted in synthetic_module — feature abandoned")

def test_abandoned_6():
    """abandoned: tests a feature 'experimental_widget_6' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget6
    except ImportError:
        raise AssertionError(f"ExperimentalWidget6 was reverted in synthetic_module — feature abandoned")

def test_abandoned_7():
    """abandoned: tests a feature 'experimental_widget_7' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget7
    except ImportError:
        raise AssertionError(f"ExperimentalWidget7 was reverted in synthetic_module — feature abandoned")

def test_abandoned_8():
    """abandoned: tests a feature 'experimental_widget_8' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget8
    except ImportError:
        raise AssertionError(f"ExperimentalWidget8 was reverted in synthetic_module — feature abandoned")

def test_abandoned_9():
    """abandoned: tests a feature 'experimental_widget_9' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget9
    except ImportError:
        raise AssertionError(f"ExperimentalWidget9 was reverted in synthetic_module — feature abandoned")

def test_abandoned_10():
    """abandoned: tests a feature 'experimental_widget_10' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget10
    except ImportError:
        raise AssertionError(f"ExperimentalWidget10 was reverted in synthetic_module — feature abandoned")

def test_abandoned_11():
    """abandoned: tests a feature 'experimental_widget_11' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget11
    except ImportError:
        raise AssertionError(f"ExperimentalWidget11 was reverted in synthetic_module — feature abandoned")

def test_abandoned_12():
    """abandoned: tests a feature 'experimental_widget_12' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget12
    except ImportError:
        raise AssertionError(f"ExperimentalWidget12 was reverted in synthetic_module — feature abandoned")

def test_abandoned_13():
    """abandoned: tests a feature 'experimental_widget_13' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget13
    except ImportError:
        raise AssertionError(f"ExperimentalWidget13 was reverted in synthetic_module — feature abandoned")

def test_abandoned_14():
    """abandoned: tests a feature 'experimental_widget_14' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget14
    except ImportError:
        raise AssertionError(f"ExperimentalWidget14 was reverted in synthetic_module — feature abandoned")

def test_abandoned_15():
    """abandoned: tests a feature 'experimental_widget_15' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget15
    except ImportError:
        raise AssertionError(f"ExperimentalWidget15 was reverted in synthetic_module — feature abandoned")

def test_abandoned_16():
    """abandoned: tests a feature 'experimental_widget_16' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget16
    except ImportError:
        raise AssertionError(f"ExperimentalWidget16 was reverted in synthetic_module — feature abandoned")

def test_abandoned_17():
    """abandoned: tests a feature 'experimental_widget_17' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget17
    except ImportError:
        raise AssertionError(f"ExperimentalWidget17 was reverted in synthetic_module — feature abandoned")

def test_abandoned_18():
    """abandoned: tests a feature 'experimental_widget_18' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget18
    except ImportError:
        raise AssertionError(f"ExperimentalWidget18 was reverted in synthetic_module — feature abandoned")

def test_abandoned_19():
    """abandoned: tests a feature 'experimental_widget_19' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget19
    except ImportError:
        raise AssertionError(f"ExperimentalWidget19 was reverted in synthetic_module — feature abandoned")

def test_abandoned_20():
    """abandoned: tests a feature 'experimental_widget_20' that was reverted before ship."""
    try:
        from synthetic_module import ExperimentalWidget20
    except ImportError:
        raise AssertionError(f"ExperimentalWidget20 was reverted in synthetic_module — feature abandoned")

# ─── Category 5: quarantine-candidate (timing-dependent flakes) ──────────

def test_quarantine_candidate_1():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_2():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_3():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_4():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_5():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_6():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_7():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_8():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_9():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_10():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_11():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_12():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_13():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_14():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_15():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_16():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_17():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_18():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_19():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

def test_quarantine_candidate_20():
    """quarantine-candidate: race-condition-shaped failure (deterministic in fixture)."""
    start = time.monotonic()
    # Simulate: assertion depends on elapsed time being below a threshold that's
    # always exceeded in the fixture (real flakes pass on retry; this one is
    # deterministic for the fixture's purposes)
    elapsed = time.monotonic() - start + 0.000001
    assert elapsed < 0.0000001, f"timing-dependent assertion failed (elapsed={elapsed})"

